# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='conditions',
            field=models.CharField(max_length=128),
        ),
    ]
