# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('reactions', '0002_auto_20171125_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='receiving',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='classes.OrganicClass'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='organic_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organic_class', to='classes.OrganicClass'),
        ),
    ]
