# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0005_receivingreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reaction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reactions'),
        ),
        migrations.AddField(
            model_name='receivingreaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivingreaction',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='reactions'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='materials',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='products',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='receivingreaction',
            name='materials',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='receivingreaction',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='receivingreaction',
            name='products',
            field=models.CharField(max_length=256),
        ),
    ]
